### ISSUE TITLE
OGS Error and hidden games

### ISSUE THREAD

**Issue by bqv** [acristescu/OnlineGo#119]
I currently have 13 games per the web ui. App only shows 11, and errors out on sync. Other games seem to function fine, but nothing related to my games with the last two users shows up. One of them has the multibyte characters %E4%BA%97%E4%BA%97 in their name - Unicode error?

**Comment by acristescu** [comment]
Hi @bqv , thank you for the bug report. I doubt that Unicode is the culprit, probably some weird response in from the server. Since you've built the app in the past, can you kindly look in logcat and post the error here? Anything on the Error channel should be relevant.

Alternatively, if you can provide your OGS user ID, I can try pulling the logs from firebase, but that's a lot less reliable.

**Comment by bqv** [comment]
Looked through logcat '*:D' already cause I figured I might be able to spot an API change, no luck though. I'm also not sure if that's because my repo has no functioning firebase support, because my debug build doesn't show the error screen, but does still hide those games. I'm somewhat stumped, but my OGS is [710261](https://online-go.com/player/710261/frony) if you might have any better inklings.

Note, 11 actual games now, 9 in app (just finished two)

**Comment by acristescu** [comment]
Spot the difference between your game 8 and game 9 time controls:
![image](https://user-images.githubusercontent.com/2835035/140842717-eb99bb2e-e213-4f34-9963-9a3cc5aebf60.png)
![image](https://user-images.githubusercontent.com/2835035/140842768-4c3137af-9fd5-40b0-8198-a406a20ea587.png)
I swear to god the server is trolling me. Only last week I fixed a bug in which it was sometimes sending 0/1 instead of true/false...

**Comment by acristescu** [comment]
Fixed in next version (@bqv you can pull the latest commit if you want to roll your own build until then)

**Comment by bqv** [comment]
Amazing :D works for me now, closing

**Comment by bqv** [comment]
Beat me to it...
