### ISSUE TITLE
LAN battle

### ISSUE THREAD

**Issue by lisxian** [acristescu/OnlineGo#132]
22/5000 
Dear developers, can you finish the LAN battle later?

**Comment by MathieuDreano** [comment]
What do you mean? 😅

**Comment by lisxian** [comment]
I mean is it ok connect LAN and play this game after? It must be awesome if play chess go through two mobile phones connected WIFI or Bluetooth.

**Comment by acristescu** [comment]
I don't think that in 2022 there is any reasonable use case for two phones to be not connected to the internet, so a LAN battle would not make sense. It would also require a lot of work to reproduce part of the functionality that OGS offers. Two friends on two different phones can play against each other by simply issuing a challenge.

Perhaps @lisxian is confused because he can't find the option to challenge his friend through OGS, and indeed we could possibly make that option a bit more visible, but a LAN battle mode is not necessary IMHO.

**Comment by lisxian** [comment]
You are absolutely right. That's what I mean
