### ISSUE TITLE
Inconsistent ranks

### ISSUE THREAD

**Issue by d-korni** [acristescu/OnlineGo#21]
Unless I'm reading something wrongly, there seems to be an issue with the ranks in the latest beta.

See two attached images.

![screenshot_online_go_20180624-165828](https://user-images.githubusercontent.com/33361462/41820855-168381da-77d0-11e8-9b96-e8faaf0ba5f7.png)
![screenshot_online_go_20180624-165819](https://user-images.githubusercontent.com/33361462/41820856-16aa0c38-77d0-11e8-9ac4-cff68cdfaaaf.png)

**Comment by acristescu** [comment]
Thank you for the report, but let me put it this way... the API is showing its age. Different calls return different values for the ratings, some of the according to the old formula, some of them according to the new one :( Also, there are no less than 10 different ratings even if you do decide which formula to use, hence it's a mess.

At the moment the only page that shows this problem is the spectate page, which I will be retiring soon. Hence, sadly, I will probably not find the time to fix this...

**Comment by d-korni** [comment]
Definitely sounds like it's not worth fixing.
PS. Loving the analysis tool! :)
