### ISSUE TITLE
Building OnlineGo

### ISSUE THREAD

**Issue by hadim** [acristescu/OnlineGo#24]
Hello,

I am trying to build the app with Android Studio (latest version) but the build fails here : https://github.com/hadim/OnlineGo/blob/053f2af7f3221ee60a2df612a2a6c64b58caae1d/app/build.gradle#L55

The build needs the env variable `SECRET_KEY` to be set. I don't understand what the `generateGoogleJson` is exactly doing. Any chance we can build the app without it?

ping @acristescu

**Comment by hadim** [comment]
By the way, your app is really great and professional-looking. I am surprised it is not more advertised on the OGS website. Did you get in touch with the developers so they can put a link? Maybe it could also become an "official" Android client.

**Comment by hadim** [comment]
I have the same error with Travis: https://travis-ci.org/hadim/OnlineGo/builds/420267869#L2178

**Comment by acristescu** [comment]
Hi @hadim, I removed the weird encryption of the `google-services.json` file I was using there. You shouldn't get that error anymore, but you will still need to generate a `google-services.json` file yourself since it's a secret. The same will be needed for the secret app id that is used to identify with online-go.com (since it's a secret too).

I'm afraid I have almost no experience with open-source projects, so I don't really know how to handle those things, but I am pretty sure I shouldn't just commit them to the source control.

PS: Thank you for the travis idea, but bitrise is already implemented (appcenter was implemented too, but it stopped working at some point... microsoft...)

**Comment by hadim** [comment]
Hi @acristescu.

About the `google-services.json` file, according to a Google engineer, it's ok for a project like that to commit it into the repo: https://groups.google.com/forum/#!msg/firebase-talk/bamCgTDajkw/uVEJXjtiBwAJ

I think it would decrease the entry barrier to develop this Android client (less setup for the new user in order to start contributing).

As for open-source projects, it's ok if it's new for you, it's already a big step you made it open-source. Congrats for this!

I don't have a lot of experience with Android dev but I have a strong background with Python, Java and more genrally with open source projects so I would be happy to help to develop the app (once I am comfortable enough with the code).

About Travis, I answer here: https://github.com/acristescu/OnlineGo/pull/25
