### ISSUE TITLE
Forum announcement

### ISSUE THREAD

**Issue by hadim** [acristescu/OnlineGo#27]
I think it would be nice to make a post announcement of the client on the OGS forum: https://forums.online-go.com/

I know the app is already being discussed in some threads there but those are general android client threads with a lot of posts without a good visibility for the project.

The post should highlight the Android Store URL and the Github URL. It should also highlight the current features of the app as well as the ones in development and welcome anyone to report bugs or contribute to the code.

You could also ping the OGS developer to know if they want to advertise it on their website. 

I can write the post if you want.

ping @acristescu

**Comment by acristescu** [comment]
This was discussed a few times, including with the admins of OGS. They said that they will think about advertising the app "once it is public" and "trustworthy". Which is fair enough. I think for this to be considered MVP it needs at the very least chat and a better finished game UI. I would like to have some sort of tutorial for people not familiar with the game. I tried contacting the creator of http://www.learngo.co.uk/ which has the best english tutorial I could find asking if I could use his material but got no reply.

I held back in creating a separate thread for the client since that is a one-time-only advertising opportunity. Last time somebody created such a thread I had a huge upshot in users but most of them just quit using the app shortly because it was not ready (and it crashed like crazy back then). Once I am satisfied the app is "good enough" I will make the post, I do think now we're finally getting close, but are not quite there yet.

**Comment by hadim** [comment]
Ok I got your point, it makes totally sense.
