### ISSUE TITLE
[Feature request] show new chat message in home screen

### ISSUE THREAD

**Issue by MielsvS** [acristescu/OnlineGo#34]
Sometimes your opponent hasn't made a move (so it's not your turn yet), but he has made a remark in the chat.

At the moment you need to enter the game to see if there's a new message in chat. Might be practical to show new messages in the home screen.

Just a quick mock up as a suggestion:
![image](https://user-images.githubusercontent.com/15874425/47950790-84534a80-df57-11e8-9f00-7dbc54d39d26.png)

**Comment by MielsvS** [comment]
> Hey man, thank you for the suggestion. (...) I simply was not able to find the time to do so :|
Sure, no problem! I'm aware this is just a side project/hobby for you. Just throwing in my 2 cents, up to you if/how/when you act on it. (and I can also blame myself, shouldn't have distracted you by playing a game ;)).

**Comment by acristescu** [comment]
@MielsvS not sure if you're even using the app anymore mate, but the *next* version (not yet released) will have this:

![Screenshot_1587648724](https://user-images.githubusercontent.com/2835035/80104708-73ddc800-856f-11ea-9997-1c6087333399.png)

Mind you, it will not check for new messages in the background, as due to the server's limitations that would waste a TON of battery and bandwidth for people with many games/messages, but it will check when you start the app (for games that are not finished yet).

**Comment by acristescu** [comment]
@MielsvS not sure if you're even using the app anymore mate, but the *next* version (not yet released) will have this:

![Screenshot_1587648724](https://user-images.githubusercontent.com/2835035/80104708-73ddc800-856f-11ea-9997-1c6087333399.png)

Mind you, it will not check for new messages in the background, as due to the server's limitations that would waste a TON of battery and bandwidth for people with many games/messages, but it will check when you start the app (for games that are not finished yet).

**Comment by MielsvS** [comment]
Haha, haven't been playing Go a lot lately, last match was a couple of weeks ago. But thanks for the update &  implementing the feature. Thanks for creating this app and improving it even further!

**Comment by MielsvS** [comment]
Little feedback on this though:
> it will check when you start the app (for games that are not finished yet).
Not checking in the background is manageable, agree on your pov.
But... Could you add a threshold of a day or a week after the game has finished? It's not uncommon for me to send a message after the game. To congratulate, or to ask for advice.

**Comment by acristescu** [comment]
Yeah, I was considering doing something like that next...

**Comment by acristescu** [comment]
Implemented that as well. I now look for the games that were finished in the past 5 days (max 25) and connect to them as well... Hopefully that will be enough, although I am sure there will be people that will say they are so chatty that they keep talking months after their ear reddening move :)

**Comment by popz73** [comment]
Hi Alex,
This feature is good but makes one bug much more annoying: is there a way to avoid showing all chat messages as "new" everytime a new app version is pushed?

I play an average of 20 correspondence games simultaneously, and today woke up to 20 chat icons highlighting the old "hi have fun" of move 1
