### ISSUE TITLE
Support for open challenges

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#59]
Hi Alex,
For game creation, today the app supports

- "Automatch" (equivalent to the "quick match" of the website)
- "Custom" (where you can target a specific user - equivalent to Challenging someone on the website)

It lacks the 3rd option, which I believe is the most used (certainly the one I use the most): the possibility to issue open challenges with custom settings (equivalent to the Custom/Create feature )

I started looking into this while submitting pr #58 , but wanted to check with you for the approach:
-> what about having a 3rd button for this? we would have
- "Automatch" (unchanged)
- "Challenge" (renaming the "Custom")
- "Custom" (new button)

"Custom" would be a mix of the two others - a settings picker similar to Challenge, but a subscription model and "open challenge" card view similar to the ones after submitting an Automatch.

**Comment by acristescu** [comment]
Hy @popz73,

Thank you for looking into this. I hope you're not going to take this the wrong way, but I don't think that implementing this is a good idea. There are several reasons for this:

- Adding the ability to create custom challenges kinda implies the ability to accept them. This WAS actually implemented in the game about 5 years ago and some remnants of that code is still there, although marked with `@Obsolete` (see ChallengesFragment). This didn't work out very well because:

  - it is a very old-fashioned way of doing things. Mobile users generally expect competitive gaming services to auto-match you with your opponent.
  - It was very hard to tap on things, as the list was very dynamic (the challenges kept appearing and disappearing). This made misclicks common and also it was quite frustrating when you couldn't accept something in time
- The whole ethos of the app is to be simple. The website has some 10 ways of getting games (!) Such as automatch, ladder challenges, open challenges, tournaments, search graph, direct challenges, bot games etc. This IMHO needlessly complicates matters and actually greatly harms the community by fragmenting the user base and thus greatly increasing the queue times for automatches.
- it could be argued that rated games should only be played with standard settings and without you picking your opponents.

What we really need here is way of actually automagically matching a user that has issued an automatch request with any open challenges that have been issued by other players, thus reducing their queuing time.

In any case, I would rather we don't compound the problem by allowing yet more people to issue open challenges instead of using automatch.

**Comment by popz73** [comment]
ok I understand
