### ISSUE TITLE
"what's new" dialog appears every time the app is launched

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#65]
doesn't seem to be intentional.. once the user has read/dismissed it, it becomes a hindrance to have it at every app launch

**Comment by popz73** [comment]
note that low-memory phones have the app cycle out of memory often, so this can be extremely annoying. I'm having it often in my old-ish Mi A1

**Comment by acristescu** [comment]
That is definitely not intended and it would surely be quite annoying. It was meant to show only once in this version and after that only show every time the string changes. That's how it works for my phone and all the emulators I've tried it on, so it might be that your particular phone has a problem with saving that text.

Can you please try and debug the issue? I cannot since:

- I can't reproduce it
- I've started a new contract yesterday and I can't spend much time on this right now.

The most likely culprit is the fact that I'm saving the whole text in preferences. Perhaps that is just too long? A good fix would be to just save a hash of the string since we're interested only if the string changed, and it's kinda bad programming in my part that I didn't do it like that from the start :)

**Comment by popz73** [comment]
weird.. sure I'll look into it, shouldn't be hard to debug. 
(and congrats on the new contract!)

**Comment by popz73** [comment]
good tip on the hash @acristescu , hashing the string completely solves the issue..

I'm very puzzled by this, though. My phone may be old, but not so old that it can't store a string... wtf android?

**Comment by popz73** [comment]
should we actually do a new "what's new" string for this bugfix?

**Comment by alexmitrani** [comment]
This is also happening to me.  It is annoying because when I turn my phone on in the morning, it doesn't display move notifications until I open the app and select "dismiss" on the "what's new" box.
