### ISSUE TITLE
[Question] Will notifications work without Google Play Services?

### ISSUE THREAD

**Issue by njfox** [acristescu/OnlineGo#71]
I'm considering using this app on an Android phone without google play services and I was curious if notifications will work without it. Most apps use firebase for push notifications, is that the case with this client?

I haven't had a chance to test it yet because I'm trying to work around build issues with play services and crashlytics.

Thanks!

**Comment by acristescu** [comment]
We're not using push notifications because the server does not support them. Hence some functionality should be available without play services, though I haven't tested them.

**Comment by njfox** [comment]
Thanks! Does the app poll for updates then? Or is there no functionality for notifying you that its your turn when the app is in the background?

**Comment by acristescu** [comment]
It is sadly just polling. It's done using the Android WorkManager so that it's respectful of Doze and thus doesn't eat too much battery, however it does mean there is a significant delay between when your opponent moves and when you're receiving the notification.

If you can convince the anoek and matburt to implement push notification on the website I'll be more than happy to implement them here.

**Comment by njfox** [comment]
Polling is perfect for my usecase actually, since there are no google play services installed for push notifications. I'll happily upvote feature requests for the server to support them though.

Thanks again!
