### ISSUE TITLE
new icons in game screen are not compatible with Dark mode

### ISSUE THREAD

**Issue by popz73** [acristescu/OnlineGo#84]
Something that was forgotten in the new release.

**Comment by acristescu** [comment]
yes, I noticed that after the release. The background of the app icon also has a different color if the device is in dark mode (blue instead of red).

**Comment by popz73** [comment]
Hi Alex, FYI the new Analysis button is funky too. When it's *disabled*, it displays badly in both light and dark modes. Don't think it deserves a bug for itself, you might want to correct it along with the others.

**Comment by acristescu** [comment]
Well, this is what I meant that adding dark mode increases development time by at least 30% for new features :) Can we have a list of the offending icons please? So far I have:

- "clock" icon
- territory icon
- analysis disabled
- main app icon has blue instead of red background on dark theme device

**Comment by acristescu** [comment]
Fixed the 4 buttons above (in next version)
