### ISSUE TITLE
Game chat unread count should be lower

### ISSUE THREAD

**Issue by pdg137** [acristescu/OnlineGo#96]
As a new user I was excited to see the game chat unread counter. It's so hard to notice messages on the official website! But (and I'm assuming the server doesn't give you this; it's something you're just keeping track of internally) it shouldn't default to saying that all of my messages are unread. In particular if I already replied to the last message, the count should almost certainly be zero. Maybe just start it at zero by default?

**Comment by acristescu** [comment]
Yes, I thought about this improvement. Presumably if you've replied you've at least read the messages up to that point. So it should only mark as unread the messages after your last reply.

It is doable, but not trivial. The difficulty comes from how the messages are received. There is no `get messages` request as you might expect, instead you connect through websockets to the game's chat channel and then the server starts sending all the messages, one-by-one.  You don't really know how many messages there are or when the server is done sending you the chat history. Yes, really!

That being said, it could be done with a bit of fiddling...

**Comment by pdg137** [comment]
Are they sent out of order?

**Comment by acristescu** [comment]
I implemented it so that it marks as read all messages that are older than the last message you sent. This should alleviate the problem a lot, but there is no way to know if you've seen the message on the website and just not replied, that will still show up as unread. That's the best I can reasonably do without backend changes. New build coming soon.
